version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - auth-network

  auth-service:
    build: ./backend
    environment:
      DB_CONNECTION: "host=postgres user=admin password=admin dbname=authdb sslmode=disable"
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - auth-network

volumes:
  postgres-data:

networks:
  auth-network:
    driver: bridge
